# Generated by Django 5.2.4 on 2025-11-06 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_vuelo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['fecha_salida']},
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('vuelo', 'numero')},
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='tripulacion',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'AD'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vuelo',
            index=models.Index(fields=['origen', 'destino'], name='gestion_vue_origen_25a1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vuelo',
            index=models.Index(fields=['fecha_salida'], name='gestion_vue_fecha_s_3f8d62_idx'),
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='clase',
        ),
    ]
