# Generated by Django 5.2.4 on 2025-11-11 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_vuelo_options_alter_asiento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='reserva_unica_por_pasajero_y_vuelo',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='precio_final_positivo',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='codigo_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='equipaje_bodega',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='equipaje_mano',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio_final',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='requerimientos_especiales',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='codigo_barra',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='gestion.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='tripulacion',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'AD'}, related_name='vuelos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
