# Generated by Django 5.2.4 on 2025-11-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='codigo_barra',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
